name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: /usr/local/bundle/gems
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}

      - uses:  helaili/jekyll-action@v2
        with:
          jekyll_src: blog
          token: ${{ secrets.GITHUB_TOKEN }}
